update for 1.4.3521
Ludeon/RimWorld-ChineseTraditional pull request #157
Opened 2022-10-19 05:35 UTC by SCThunder

# 主旨

(新增/修改)(核心遊戲/皇權DLC/理念DLC)翻譯

## 更新內容

2022-10-19 07:28 UTC, SCThunder commented
把更換的部份也翻好了，只剩TODO

2022-10-20 00:38 UTC, Darkborderman commented
> 把更換的部份也翻好了，只剩TODO

TODO 也可以先進版, 之後再來翻

2022-10-20 00:42 UTC, Darkborderman commented on Core/DefInjected/ResearchProjectDef/ResearchProjects_2_Electricity.xml
> +  <ColoredLights.label>先進燈</ColoredLights.label>
> 並使立燈耗電量減半
看到這個覺得像是省電燈, 但是改變顏色就不太一樣了, 感覺像是 `省電色燈` 之類的東西

2022-10-20 00:43 UTC, Darkborderman commented
> 把TODO先放上來大家翻譯，沒有TODO的更動部份我自己翻好再放上來
應該會在假日做處理, 我會把 DLC 翻譯也丟上來

2022-10-20 00:50 UTC, Darkborderman commented on Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
> +  <Hospitality_Util_Worker.LetterTextGuestLost.slateRef>需要你護衛的[letterSubject]回歸自然了。[remainingWillNowLeave][failLetterEndingCommon]</Hospitality_Util_Worker.LetterTextGuestLost.slateRef>
應該是野化了, 他是一種精神崩潰會發生的狀態

https://github.com/Ludeon/RimWorld-ChineseTraditional/blob/d5a15c4c5b31ade03ca1329f55fd0765d3cdfd94/Core/DefInjected/MentalBreakDef/MentalStates_Mood.xml

2022-10-20 00:51 UTC, Darkborderman commented on Royalty/DefInjected/QuestScriptDef/Script_Intro_Wimp.xml
> +  <Intro_Wimp.LetterTextGuestLost.slateRef>需要你保護的{SUBJECT_definite}回歸自然了。[failLetterEndingCommon]</Intro_Wimp.LetterTextGuestLost.slateRef>
同上

2022-10-20 00:55 UTC, Darkborderman requested changes
上面幾個東西看一下 沒有問題或改好就ＯＫ了

2022-10-20 01:05 UTC, SCThunder commented on Core/DefInjected/ResearchProjectDef/ResearchProjects_2_Electricity.xml
> +  <ColoredLights.label>先進燈</ColoredLights.label>
化繁為簡，最簡單、籠統的用字`高級燈`如何

2022-10-20 01:07 UTC, SCThunder commented
順便更新到1.4.3522
純粹多了毒霧霾的心情

2022-10-20 01:07 UTC, merged