JobDef
Ludeon/RimWorld-ChineseTraditional pull request #174
Opened 2022-10-24 13:00 UTC by shiuanyue

2022-10-24 15:39 UTC, SCThunder commented on Biotech/DefInjected/JobDef/Jobs_Learning.xml
> +  <NatureRunning.reportString>自然運行。</NatureRunning.reportString>
應該是在大自然/室外奔跑
可以說成`探索大自然`

2022-10-24 15:39 UTC, SCThunder commented on Biotech/DefInjected/JobDef/Jobs_Misc.xml
> +  <PrisonerBloodfeed.reportString>以TargetA為食。</PrisonerBloodfeed.reportString>
餵食TargetA

2022-10-24 15:39 UTC, SCThunder commented on Biotech/DefInjected/JobDef/Jobs_Childcare.xml
> +  <FertilizeOvum.reportString>TODO</FertilizeOvum.reportString>
對TargetA授精。

整件事是︰1. 從16歲以上女性身上動手術，取卵子 2. 男殖民者就會fertilizing TargetA.，直接整個人對著那盤卵子fertilizing。

2022-10-24 15:41 UTC, SCThunder commented
Biotech\DefInjected\LearningDesireDef\LearningDesires.xml

如果先翻譯這個有助理解小孩行為

2022-10-25 05:54 UTC, Darkborderman commented
感覺是 CRLF 和 LF 跑掉了導致整個看起來都是修改

2022-10-25 05:55 UTC, Darkborderman commented on Biotech/DefInjected/JobDef/Jobs_Learning.xml
> +  <Lessontaking.reportString>吸取教訓。</Lessontaking.reportString>
這個沒改到

2022-10-25 06:09 UTC, shiuanyue commented on Biotech/DefInjected/JobDef/Jobs_Learning.xml
> +  <Lessontaking.reportString>吸取教訓。</Lessontaking.reportString>
我點入編輯 是有改的

2022-10-25 13:08 UTC, SCThunder requested changes

2022-10-25 13:08 UTC, SCThunder commented on Biotech/DefInjected/JobDef/Jobs_Learning.xml
> +  <Lessontaking.reportString>吸取教訓。</Lessontaking.reportString>
上課中。

2022-10-25 13:08 UTC, SCThunder commented on Biotech/DefInjected/JobDef/Jobs_Learning.xml
> +  <Lessongiving.reportString>上課中。</Lessongiving.reportString>
打錯位置了，這是授課中。

2022-10-25 13:09 UTC, SCThunder commented on Biotech/DefInjected/JobDef/Jobs_Learning.xml
> +  <Lessontaking.reportString>吸取教訓。</Lessontaking.reportString>
你打錯位置了啦

2022-10-25 13:21 UTC, merged