Buildings
Ludeon/RimWorld-ChineseTraditional pull request #178
Opened 2022-10-27 08:30 UTC by peter4370

# 主旨

(新增)(生機DLC)翻譯

## 更新內容

Buildings_Furniture.xml
Letters.xml 中的 children 部分
企業無人機改成符合中文使用習慣的社畜 [urban dictionary](https://www.urbandictionary.com/define.php?term=corporate%20drone)

2022-10-27 13:09 UTC, peter4370 commented on Biotech/Keyed/Letters.xml
> +  <LetterPartNameBaby>嬰兒被取了暫時的名字{0_nameFull}。你最晚可以在出生後{1}改名。</LetterPartNameBaby>
我改 乳名好了 [wiki](https://zh.wikipedia.org/wiki/%E4%B9%B3%E5%90%8D)

2022-10-27 14:45 UTC, SCThunder requested changes
有兩個大修
寶寶 => 嬰兒
小孩 => 兒童
因為這些是具體的成長階段，像模擬市民一樣。

2022-10-27 14:45 UTC, SCThunder commented on Biotech/DefInjected/ThingDef/Buildings_Furniture.xml
> +  <SchoolDesk.description>成人可以用來教小孩的桌子。</SchoolDesk.description>
成人可以在此桌子為小孩上課。

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <LetterVatSillbornNoParents>在發育艙內成長為嬰兒的胚胎是個死胎。</LetterVatSillbornNoParents>
在發育艙內成長為嬰兒的胚胎夭折了。

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <LetterVatStillborn>{0_nameDef}和{1_nameDef}在發育艙內成長為嬰兒的胚胎是個死胎。</LetterVatStillborn>
{0_nameDef}和{1_nameDef}在發育艙內的胚胎成長為嬰兒但夭折了。

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <LetterColonistPregnancyLaborLabel>{0_labelShort}臨產了！</LetterColonistPregnancyLaborLabel>
{0_labelShort}臨盆在即!

我覺得臨盆比較常見(個人看法)，臨盆在即 四字詞也比較帥

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <LetterColonistPregnancyLabor>{0_labelShort}臨產了！在生產前幾個小時會開始有宮縮。生產過程中會經歷數個階段的困難和危險。\n\n爲了增加接生的成功率，召集一位醫生和其他人來幫忙接生。選取{0_labelShort}並按下「召集接生」來開始流程。</LetterColonistPregnancyLabor>
臨產 => 臨盆

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <LetterPartNameBabyAdopt>嬰兒被取了乳名{0_nameFull}。在嬰兒出生滿{1}之前你可以隨時改名。</LetterPartNameBabyAdopt>
在嬰兒出生滿{1}歲

這邊就只有數字

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <LetterPartNameBaby>嬰兒被取了乳名{0_nameFull}。你最晚可以在出生後{1}改名。</LetterPartNameBaby>
你最晚可以在出生後{1}內

{1}出來的效果應該是「一天」之類，有單位的字

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <BirthdayGrowthMoment>{PAWNNAME}的轉捩點</BirthdayGrowthMoment>
我是翻 成長時刻 較直白且準確 (看起來也像模擬市民用字)

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <BirthdayPickPassion>為{0_nameDef}選擇一項技能來提升{0_possessive}熱情</BirthdayPickPassion>
為{0_nameDef}提升一項技能的熱情

2022-10-27 14:45 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <SelectPassionsPlural>選擇{0}項特性。</SelectPassionsPlural>
錯字

選擇{0}項熱情。

2022-10-27 14:50 UTC, SCThunder commented on Biotech/Keyed/Letters.xml
> +  <BirthdayMakeChoices>選擇完自動關閉</BirthdayMakeChoices>
感覺這個有可能玩的時候會發現怪怪的

2022-10-28 02:09 UTC, peter4370 commented on Biotech/Keyed/Letters.xml
> +  <BirthdayMakeChoices>選擇完自動關閉</BirthdayMakeChoices>
這句我猜是還沒選完就按下OK會出現 我改成`選擇完即可關閉`

2022-10-28 06:17 UTC, SCThunder approved these changes

2022-10-28 13:23 UTC, merged