Update GameplayCommands.xml
Ludeon/RimWorld-ChineseTraditional pull request #182
Opened 2022-10-28 07:19 UTC by Lak4CYUT

先翻看的懂的.. QQ

# 主旨

(新增/修改)(核心遊戲/皇權DLC/理念DLC/生機DLC)翻譯

## 更新內容

2022-10-28 07:29 UTC, SCThunder requested changes

2022-10-28 07:29 UTC, SCThunder commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandAutoRepair>主動修復</CommandAutoRepair>
自動

2022-10-28 07:29 UTC, SCThunder commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandAutoRepairDesc>若啟用，御機使會主動修復機械人。修復機械人會消秏它的能量。</CommandAutoRepairDesc>
自動

自動自覺嘛

2022-10-28 07:29 UTC, SCThunder commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandSelectAllMechs>選取所有機械人</CommandSelectAllMechs>
機械族

目前先統一方便以後改

2022-10-28 07:29 UTC, SCThunder commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandSelectAllMechsDesc>選取所有由此御機使操控的機器人。</CommandSelectAllMechsDesc>
機械族

2022-10-28 07:29 UTC, SCThunder commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandToggleTurretDesc>開關砲塔是否自動開火攻擊。\n\n若關閉，砲塔將不會自動開火攻擊。此功能有助於進行偷襲敵人的行動。</CommandToggleTurretDesc>
開關砲塔 => 設定砲塔

通順用字

2022-10-29 15:37 UTC, SCThunder commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandToggleTurretDesc>開關砲塔是否自動開火攻擊。\n\n若關閉，砲塔將不會自動開火攻擊。此功能有助於進行偷襲敵人的行動。</CommandToggleTurretDesc>
看到有個舊的翻譯是用切換，那就切換吧
```suggestion
  <CommandToggleTurretDesc>切換砲塔是否自動開火攻擊。\n\n若關閉，砲塔將不會自動開火攻擊。此功能有助於進行偷襲敵人的行動。</CommandToggleTurretDesc>
```

2022-10-30 09:31 UTC, Lak4CYUT commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandAutoRepairDesc>若啟用，御機使會主動修復機械人。修復機械人會消秏它的能量。</CommandAutoRepairDesc>
我覺得在講人類行為用 "自動" 好像怪怪的？

2022-10-30 09:49 UTC, Lak4CYUT commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandSelectAllMechs>選取所有機械人</CommandSelectAllMechs>
```suggestion
  <CommandSelectAllMechs>選取所有機械族</CommandSelectAllMechs>
```

2022-10-30 09:49 UTC, Lak4CYUT commented on Biotech/Keyed/GameplayCommands.xml
> +  <CommandSelectAllMechsDesc>選取所有由此御機使操控的機器人。</CommandSelectAllMechsDesc>
```suggestion
  <CommandSelectAllMechsDesc>選取所有由此御機使操控的機器族。</CommandSelectAllMechsDesc>
```

2022-10-30 16:49 UTC, merged