Update Ritual_Outcomes.xml
Ludeon/RimWorld-ChineseTraditional pull request #190
Opened 2022-10-31 09:43 UTC by Lak4CYUT

幾個不確定的列在下面。

# 主旨

(新增/修改)(核心遊戲/皇權DLC/理念DLC/生機DLC)翻譯

## 更新內容

2022-10-31 12:38 UTC, SCThunder requested changes

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.description>所有的品質參數都將影響媽媽跟寶寶的健康。</ChildBirth.description>
```suggestion
  <ChildBirth.description>所有的品質倍率都將影響母親跟嬰兒的健康。</ChildBirth.description>
```

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.comps.0.labelAbstract>媽媽的年齡</ChildBirth.comps.0.labelAbstract>
```suggestion
  <ChildBirth.comps.0.labelAbstract>母親的年齡</ChildBirth.comps.0.labelAbstract>
```

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.comps.2.label>喜愛的人在場</ChildBirth.comps.2.label>
```suggestion
  <ChildBirth.comps.2.label>愛人在場</ChildBirth.comps.2.label>
```

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.comps.2.labelNotMet>喜愛的人缺席</ChildBirth.comps.2.labelNotMet>
```suggestion
  <ChildBirth.comps.2.labelNotMet>愛人缺席</ChildBirth.comps.2.labelNotMet>
```

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.extraOutcomeDescriptions.0.description>除此之外，母親有 {0_percentage} 機率在生產時死亡。</ChildBirth.extraOutcomeDescriptions.0.description>
```suggestion
  <ChildBirth.extraOutcomeDescriptions.0.description>除此之外，母親有{0_percentage}機率在分娩時死亡。</ChildBirth.extraOutcomeDescriptions.0.description>
```

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.0.label>無反應</ChildBirth.outcomeChances.0.label>
```suggestion
  <ChildBirth.outcomeChances.0.label>夭折</ChildBirth.outcomeChances.0.label>
```

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.0.description>{MOTHER_labelShort}的寶寶流產。</ChildBirth.outcomeChances.0.description>
```suggestion
  <ChildBirth.outcomeChances.0.description>{MOTHER_labelShort}的嬰兒夭折。</ChildBirth.outcomeChances.0.description>
```

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.1.description>{MOTHER_labelShort}生下一名寶寶，不幸的是寶寶看來並不健康。</ChildBirth.outcomeChances.1.description>
```suggestion
  <ChildBirth.outcomeChances.1.description>{MOTHER_labelShort}生下一名嬰兒，不幸的是嬰兒看來生病了。</ChildBirth.outcomeChances.1.description>
```

我是想把label 跟description用字一樣而已

2022-10-31 12:38 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.2.description>{MOTHER_labelShort}生下一名健康的寶寶！</ChildBirth.outcomeChances.2.description>
```suggestion
  <ChildBirth.outcomeChances.2.description>{MOTHER_labelShort}生下一名健康的嬰兒！</ChildBirth.outcomeChances.2.description>
```

2022-11-01 03:24 UTC, Lak4CYUT commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.0.description>{MOTHER_labelShort}的寶寶流產。</ChildBirth.outcomeChances.0.description>
夭折指的好像是生產下來之後才死亡？ stillborn 應該是流產或死胎？(胎死腹中？)

2022-11-01 03:26 UTC, Lak4CYUT commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.1.description>{MOTHER_labelShort}生下一名寶寶，不幸的是寶寶看來並不健康。</ChildBirth.outcomeChances.1.description>
我覺得不用強迫用一樣的字耶？畢竟 description 就是在解釋短句的 label。

2022-11-01 04:49 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.0.description>{MOTHER_labelShort}的寶寶流產。</ChildBirth.outcomeChances.0.description>
這是接生時的結果，你覺得算有沒有生產下來？

2022-11-01 05:22 UTC, SCThunder commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.1.description>{MOTHER_labelShort}生下一名寶寶，不幸的是寶寶看來並不健康。</ChildBirth.outcomeChances.1.description>
但用一樣的字也不會很突兀吧
如果沒事把詞改來改去，慢慢多起來就不知哪個才是標準了，算是一種習慣

2022-11-01 05:46 UTC, Lak4CYUT commented on Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
> +  <ChildBirth.outcomeChances.1.description>{MOTHER_labelShort}生下一名寶寶，不幸的是寶寶看來並不健康。</ChildBirth.outcomeChances.1.description>
U r boss .. XD 我等下改

2022-11-02 03:53 UTC, peter4370 approved these changes

2022-11-02 06:59 UTC, merged