Thoughts_IdeoRole.xml、Thoughts_Situational.xml 、Thoughts_Situation_Social.xml
Ludeon/RimWorld-ChineseTraditional pull request #73
Opened 2021-08-28 12:39 UTC by SyamiWago

# 主旨

(新增/修改)(核心遊戲/皇權DLC/理念DLC)翻譯

## 更新內容

2021-08-28 20:03 UTC, Darkborderman commented
對的就是這樣

2021-08-28 20:16 UTC, Darkborderman requested changes

2021-08-28 20:16 UTC, Darkborderman commented on Ideology/DefInjected/ThoughtDef/Thoughts_Situational.xml
> +  <MasochistWearingBodyStrap.stages.masochist_body_strapped.label>受虐狂的身體綑綁</MasochistWearingBodyStrap.stages.masochist_body_strapped.label>
這邊用 `受虐狂被捆綁`覺得會比較好

2021-08-28 20:16 UTC, Darkborderman commented on Ideology/DefInjected/ThoughtDef/Thoughts_IdeoRole.xml
> +  <IdeoLeaderResentmentAbhorrent.stages.0.description>接受來自 {0} 的指示是萬般可恥與可恨的。</IdeoLeaderResentmentAbhorrent.stages.0.description>
語句裏面有 `xxx {0} xxx` 因為原文是英文所以中間會有空白, 翻成中文直接 `xxx{0}xxx` 就可以了

下面類似情況的也改下吧

2021-08-28 20:16 UTC, Darkborderman commented on Ideology/DefInjected/ThoughtDef/Thoughts_Situational.xml
> +  <MasochistWearingCollar.stages.masochist_collared.label>受虐狂的頸圈</MasochistWearingCollar.stages.masochist_collared.label>
`受虐狂被束頸` 感覺比較順

2021-08-29 03:01 UTC, SyamiWago commented on Ideology/DefInjected/ThoughtDef/Thoughts_IdeoRole.xml
> +  <IdeoLeaderResentmentAbhorrent.stages.0.description>接受來自 {0} 的指示是萬般可恥與可恨的。</IdeoLeaderResentmentAbhorrent.stages.0.description>
了解

2021-08-29 03:02 UTC, SyamiWago commented on Ideology/DefInjected/ThoughtDef/Thoughts_Situational.xml
> +  <MasochistWearingCollar.stages.masochist_collared.label>受虐狂的頸圈</MasochistWearingCollar.stages.masochist_collared.label>
改好了，主要是我不知道這事件在遊戲中是發生前還是後

2021-08-29 03:09 UTC, Darkborderman commented on Ideology/DefInjected/ThoughtDef/Thoughts_Situational.xml
> +  <MasochistWearingCollar.stages.masochist_collared.label>受虐狂的頸圈</MasochistWearingCollar.stages.masochist_collared.label>
這個會是殖民者的想法, 影響mood部份(+2,-3這些)

2021-08-29 03:09 UTC, merged

2021-08-29 03:09 UTC, Darkborderman commented
Merged, thanks!