Update FloatMenu.xml
Ludeon/RimWorld-ChineseTraditional pull request #75
Opened 2021-08-28 14:38 UTC by SCThunder

# 主旨

(修改)(理念DLC)翻譯

## 更新內容

2021-08-28 20:25 UTC, Darkborderman requested changes

2021-08-28 20:25 UTC, Darkborderman commented on Ideology/Keyed/FloatMenu.xml
> +  <CantStartRitualSelectedPawnPsychicallyDeaf>{PAWN_nameDef}是失聰人士。</CantStartRitualSelectedPawnPsychicallyDeaf>
這裡不是失聰, 是`心靈障壁`

2021-08-28 20:25 UTC, Darkborderman commented on Ideology/Keyed/FloatMenu.xml
> +  <InstallRelic>安置{0}</InstallRelic>
這裡遊戲內已經有的翻譯是用`安裝`, 看要不要同步

2021-08-28 20:25 UTC, Darkborderman commented on Ideology/Keyed/FloatMenu.xml
> +  <ExtractRelic>提取{0}</ExtractRelic>
這裡遊戲內已經有的翻譯是用`取出`, 看要不要同步

2021-08-28 20:25 UTC, Darkborderman commented on Ideology/Keyed/FloatMenu.xml
> +  <ExtractRelicToInventory>提取{0}至庫存({1})</ExtractRelicToInventory>
這裡遊戲內已經有的翻譯是用`取出`, 看要不要同步

2021-08-29 02:46 UTC, SCThunder commented on Ideology/Keyed/FloatMenu.xml
> +  <InstallRelic>安置{0}</InstallRelic>
起初也覺得是安裝，不過後面安「裝」在聖物箱就不合理了，目前保留用安置

2021-08-29 02:49 UTC, Darkborderman commented on Ideology/Keyed/FloatMenu.xml
> +  <InstallRelic>安置{0}</InstallRelic>
理解 那沒有關係

2021-08-29 02:52 UTC, merged