TerrainDef
Ludeon/RimWorld-ChineseTraditional pull request #77
Opened 2021-08-28 16:04 UTC by SyamiWago

# 主旨

(新增/修改)(核心遊戲/皇權DLC/理念DLC)翻譯

## 更新內容

2021-08-28 20:39 UTC, Darkborderman requested changes

2021-08-28 20:39 UTC, Darkborderman commented on Ideology/DefInjected/TerrainDef/Terrain_Floors.xml
> +  <Carpet_MindbendA.description>精神異常風格的精美地毯，通常與吸毒有關。</Carpet_MindbendA.description>
建議統一一下同一個字的翻譯
```
mind-bending, mindbend -> 迷幻
morbid -> 亡者
spikecore -> 尖刺
```
因為有點多所以留這裡, 下面有用到的記得改

2021-08-28 20:39 UTC, Darkborderman commented on Ideology/DefInjected/TerrainDef/Terrain_Floors.xml
> +  <Tile_Transhumanist.label>六角鐵地板</Tile_Transhumanist.label>
這裡用`六角地磚`就好了

2021-08-28 20:39 UTC, Darkborderman commented on Ideology/DefInjected/TerrainDef/Terrain_Floors.xml
> +  <Tile_MorbidLimestone.label>詭異的石灰岩地磚</Tile_MorbidLimestone.label>
這邊的`的`可以省略,下面相關的也是

2021-08-28 20:39 UTC, Darkborderman commented on Ideology/DefInjected/TerrainDef/Terrain_Floors.xml
> +  <Plates_Spikecore.label>銳紋鐵地板</Plates_Spikecore.label>
這邊我在遊戲裡玩到,他不是地板(可deconstruct, 不是remove floor),用`尖刺地墊`可能會比較符合

2021-08-28 20:39 UTC, Darkborderman commented on Ideology/DefInjected/TerrainDef/Terrain_Floors.xml
> +  <Plates_Spikecore.description>具攻擊性尖刺風格的精美鐵板。</Plates_Spikecore.description>
`尖刺風格的精美地墊。`就可以了

2021-08-29 03:09 UTC, SyamiWago commented on Ideology/DefInjected/TerrainDef/Terrain_Floors.xml
> +  <Plates_Spikecore.label>銳紋鐵地板</Plates_Spikecore.label>
<!-- EN: hex tile -->
<Tile_Transhumanist.label>六角鐵地板</Tile_Transhumanist.label>

這個也改成 六角地墊 ?

2021-08-29 03:11 UTC, SyamiWago commented
改好囉

2021-08-29 03:21 UTC, merged

2021-08-29 03:21 UTC, Darkborderman commented
Merged, thanks!