理念DLC翻譯與空白修正
Ludeon/RimWorld-ChineseTraditional pull request #92
Opened 2021-09-05 14:52 UTC by SCThunder

# 主旨

## 更新內容

interaction 整頁翻譯。scarification暫譯劃禮，之後想到更好的詞再統一修正。tree connection則直譯，因為沒有靈感。
把「心眼教」改成「心視教」，「心視」blindness與「目視」sight相對，無目則心視
「改信」改成「傳教」，用作動詞更通順。皈依則是「(受者)轉換理念」的時候用的動詞。
刪除一些多出的 {變數} 前的空白

2021-09-05 16:48 UTC, SCThunder commented
追加修正︰劃痕的動詞和名詞改為「瘢痕紋身」，相關儀式為「紋禮」
順便修正眼殘看錯sacri但其實是scari XD

2021-09-05 22:25 UTC, Darkborderman commented
> # 主旨
> ## 更新內容
> 
> interaction 整頁翻譯。scarification暫譯劃禮，之後想到更好的詞再統一修正。tree connection則直譯，因為沒有靈感。
> 把「心眼教」改成「心視教」，「心視」blindness與「目視」sight相對，無目則心視
> 「改信」改成「傳教」，用作動詞更通順。皈依則是「(受者)轉換理念」的時候用的動詞。
> 刪除一些多出的 {變數} 前的空白

OK, 這些建議可以加到wiki, 之後可以方便參閱

https://github.com/Ludeon/RimWorld-ChineseTraditional/wiki/Ideology-DLC-glossary

2021-09-05 22:30 UTC, Darkborderman requested changes

2021-09-05 22:30 UTC, Darkborderman commented on Ideology/DefInjected/AbilityDef/Abilities.xml
> +  <AnimalCalm.comps.CompAbilityEffect_StopManhunter.successMessage>{INITIATOR_labelShort} 成功安撫了{RECIPIENT_labelShort}。</AnimalCalm.comps.CompAbilityEffect_StopManhunter.successMessage>
`{INITIATOR_labelShort}`後還是有空白

2021-09-06 00:07 UTC, merged

2021-09-06 00:07 UTC, Darkborderman commented
Merged, thanks!